/**
 * Client-side airport lookup over the OurAirports dataset.
 *
 * The data lives in `public/airports.json` (regenerated by
 * `scripts/buildAirports.ts`) as compact `[iata, name, city, country]` tuples.
 * It is fetched lazily — only the admin flight editor needs it — so it never
 * weighs on the traveler bundle. Search runs in-memory; there is no runtime API.
 */

export interface Airport {
  iata: string;
  name: string;
  city: string;
  country: string;
}

/** The on-disk shape: order must match `scripts/buildAirports.ts`. */
type AirportTuple = [iata: string, name: string, city: string, country: string];

/** Default number of suggestions to surface for a query. */
const DEFAULT_LIMIT = 8;

/** Inflate the compact tuple form into records, dropping malformed rows. */
export function parseAirports(raw: AirportTuple[]): Airport[] {
  return raw
    .filter((t) => Array.isArray(t) && typeof t[0] === "string" && t[0])
    .map(([iata, name, city, country]) => ({ iata, name, city, country }));
}

/**
 * The display label these fields store, e.g. "Kuala Lumpur (KUL)". Falls back to
 * the airport name when no city is recorded so the code is always shown.
 */
export function formatAirport(a: Airport): string {
  return `${a.city || a.name} (${a.iata})`;
}

/**
 * Rank airports for a free-text query. Exact/prefix IATA code matches win, then
 * city, then name; substring matches come last. Returns at most `limit` results,
 * or `[]` for a blank query.
 */
export function searchAirports(
  airports: Airport[],
  query: string,
  limit = DEFAULT_LIMIT,
): Airport[] {
  const q = query.trim();
  if (!q) return [];
  const upper = q.toUpperCase();
  const lower = q.toLowerCase();

  const scored: { a: Airport; score: number }[] = [];
  for (const a of airports) {
    const iata = a.iata.toUpperCase();
    const city = a.city.toLowerCase();
    const name = a.name.toLowerCase();

    let score: number;
    if (iata === upper) score = 0;
    else if (iata.startsWith(upper)) score = 1;
    else if (city.startsWith(lower)) score = 2;
    else if (name.startsWith(lower)) score = 3;
    else if (city.includes(lower)) score = 4;
    else if (name.includes(lower)) score = 5;
    else continue;

    scored.push({ a, score });
  }

  scored.sort((x, y) => x.score - y.score || x.a.city.localeCompare(y.a.city));
  return scored.slice(0, limit).map((s) => s.a);
}

/** Module-level cache so the dataset is fetched and parsed at most once. */
let cache: Promise<Airport[]> | null = null;

/** Lazily fetch and parse the airport dataset (cached for the session). */
export function loadAirports(): Promise<Airport[]> {
  if (!cache) {
    const url = `${import.meta.env.BASE_URL}airports.json`;
    cache = fetch(url)
      .then((res) => {
        if (!res.ok) throw new Error(`airports.json: ${res.status}`);
        return res.json() as Promise<AirportTuple[]>;
      })
      .then(parseAirports)
      .catch((err) => {
        // Reset so a later attempt can retry rather than reusing a rejection.
        cache = null;
        throw err;
      });
  }
  return cache;
}
